# Generated by Django 4.2.5 on 2023-10-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='assighn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.ManyToManyField(blank=True, related_name='assignment_name', to='students.present1')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_teachers', to='teacher.present')),
            ],
        ),
    ]
